### ISSUE TITLE
Can't perform makemigrations Jango when using JWT

### ISSUE THREAD

**Issue by Rjayone** [GehirnInc/python-jwt#16]
Hi everyone, i faced with problem, which can't let me perform makemigrations when i'm using JWT.

The error is: 
`    from jwt import JWT, jwk_from_pem
     ImportError: cannot import name JWT
`

In the file i just import JWT & jwk_from_pem
`from jwt import JWT, jwk_from_pem`
then using `jwt = JWT()`

In the settings.py 
`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ...,
    'rest_framework',
    'jwt',
    ...,
]`

What the cause of the error above?

**Comment by yosida95** [comment]
@Rjayone Please paste `pip freeze` output in your environment.

**Comment by Rjayone** [comment]
@yosida95 solved this problem by using python**3** manage.py makemigrations
Anyway thank you for fast reply
