### ISSUE TITLE
AbstractJWKBase Should be an ABC class

### ISSUE THREAD

**Issue by sjortiz** [GehirnInc/python-jwt#20]
# Rationale
AbstractJWKBase so far is just a placeholder class that raise not implemented if a method is called in a subclass that doesn't implement the given method, this is exactly why ABC classes in python are for, therefore we should move it that way.

https://github.com/GehirnInc/python-jwt/blob/master/jwt/jwk.py#L53

**Comment by sjortiz** [comment]
@yosida95 I would like to work on this issue myself

**Comment by yosida95** [comment]
@sjortiz 

Thank you for your suggestion! Your point is correct.

I will wait for your patch on this for a month.
