### ISSUE TITLE
Improve documentation for symmetric keys

### ISSUE THREAD

**Issue by izolate** [GehirnInc/python-jwt#25]
The README states that symmetric algorithms are supported but I haven't been able to figure out how to decode them with this library. Either I'm missing something or this hasn't been implemented yet.

Either way, appreciate any help on this.

**Comment by yosida95** [comment]
You can decode a JWS signed by a symmetric key in the same way to decode one signed by a asymmetric key like below.

```python3
import jwt


jwk = {"kty": "oct", "k": "# YOUR SYMMETRIC JWK KEY #"}
key = jwt.jwk_from_dict(jwk)
instance = jwt.JWT()
instance.decode('JWT PAYLOAD', key)
```

You can also refer to the working test case at https://github.com/GehirnInc/python-jwt/blob/6e45f9d131416688b728119ea83b6ffd378b5ccf/jwt/tests/test_jwt.py#L26-L50

**Comment by yosida95** [comment]
Or you can also instantiate symmetric JWK directly as below.

```python
import jwt
from jwt.jwk import OctetJWK

key = OctetJWK(b'SYMMETRIC KEY')
instance = jwt.JWT() 
instance.decode('JWT PAYLOAD', key)
```
