### ISSUE TITLE
Conflict with PyJWT

### ISSUE THREAD

**Issue by sajozsattila** [GehirnInc/python-jwt#36]
Hello,

There is a conflict between this package and the PyJWT (https://github.com/jpadilla/pyjwt), both packages are installed in the /dist-packages/jwt.

It could be good if the two teams could come up with some solution? Or can this package installed in a different way?

Kind regards
Attila

**Comment by yosida95** [comment]
Thank you for bringing up your concern. We are aware of this name crash issue, but for now, we at @GehirnInc have decided not to fix it. See https://github.com/GehirnInc/python-jwt/issues/9#issuecomment-414175635.
