### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_kty'

### ISSUE THREAD

**Issue by Progyan1997** [GehirnInc/python-jwt#7]
I am getting this error while generating web token.

**Python Version**: 3.6
**JWT Version**: 0.5.2

**Comment by yosida95** [comment]
Please provide a minimal reprodusing snippet.

2017年7月10日(月) 16:50 Progyan Bhattacharya <notifications@github.com>:

**Comment by Progyan1997** [comment]
Solved it, it doesn't work with strings..

**Comment by yosida95** [comment]
Yes. It works only for an instance of subclasses of the `AbstractJWKBase`.

**Comment by Allan-Nava** [comment]
I got the same error:
'str' object has no attribute 'get_kty'

**Comment by yosida95** [comment]
As mentioned above, the key argument must be an instance of a subclass of `AbstractJWKBase`. Built-in `str` class is not a subclass of `AbstractJWKBase`.
