### ISSUE TITLE
name clash

### ISSUE THREAD

**Issue by davidedelvento** [GehirnInc/python-jwt#9]
Thanks to [this bug in pip](https://github.com/pypa/pip/issues/4625), installing pyjwt and jwt at the same time causes a whole lot of issues with no warning whatsoever to the poor user. Please see https://github.com/pypa/pip/issues/4625 and https://github.com/jpadilla/pyjwt/issues/282 for details.

And pretty please consider talk with the author of the other package and agree on a unique namespace.

**Comment by cal97g** [comment]
Also pip2 will install this library by the looks of it. To confirm:

`pip install jwt`

Installs this library.

```callam$ pip --version
pip 9.0.1 from /Users/callam/Documents/venvs/projectspecific/lib/python2.7/site-packages (python 2.7)```

Obviously this library breaks things, due to incompatibility with Python 2.X. Surely this library should only installed by pip3?

```File "/Users/callam/Documents/venvs/newedgeuiv/lib/python2.7/site-packages/jwt/jwk.py", line 60
    def is_sign_key(self) -> bool:```

**Comment by yosida95** [comment]
I think renaming package is a serious breaking change and will cause another confusion in package users. I don't know the actual number but it seems too small number of users that using both packages at the same time. Additionally we're using consistent name between PyPI and the package. Therefore we won't fix this problem for now.

Thank you for notifying us about the problem!

**Comment by s2t2** [comment]
I am experiencing this issue on CI using GitHub Actions.
